Repository P-juuny/OpenSource-C, pull requests merged in 2024-05, with the labels that each got.

#3 [Refactor] main, SnakeAndApple파일분리
  SnakeAndApple.py
  __pycache__/SnakeAndApple.cpython-311.pyc
  main.py
Labels: ⚙️ Refactor

#5 [Refactor] 색상상수 대문자로 변환
  SnakeAndApple.py
Labels: ⚙️ Refactor

#16 [Refactor] Green 색상명 대문자로 변환
  SnakeAndApple.py
Labels: ⚙️ Refactor

#12 [Refactor] 재시작 방법 변경 (최종 수정본)
  SnakeAndApple.py
Labels: ⚙️ Refactor

#17 [Feat] 시작페이지 UI 추가
  StartPage.py
Labels: ✨ Feature

#11 [Refactor] snake, snake_objects 자료구조 변경
  SnakeAndApple.py
Labels: ⚙️ Refactor

#27 [Feat] Color 파일, 설정페이지 추가
  .DS_Store
  Color.py
  SettingPage.py
  SnakeAndApple.py
  StartPage.py
  __pycache__/SettingPage.cpython-311.pyc
  __pycache__/SnakeAndApple.cpython-311.pyc
  main.py
Labels: ✨ Feature

#22 [refacotr]/시작페이지 이동 방법 변경
  StartPage.py
Labels: ⚙️ Refactor

#13 [Feature] 뱀이 사과를 먹었을 때 메커니즘 변경
  SnakeAndApple.py
  __pycache__/SnakeAndApple.cpython-312.pyc
Labels: ✨ Feature

#20 Refactor/18- row_h/col_w
  SnakeAndApple.py
Labels: ⚙️ Refactor

#28 [Refactor]__pycache__ 제외
  .gitignore
  __pycache__/SettingPage.cpython-311.pyc
  __pycache__/SnakeAndApple.cpython-311.pyc
Labels: ⚙️ Refactor

#23 [feature]게임 일시정지 기능추가
  .DS_Store
  SnakeAndApple.py
  __pycache__/SnakeAndApple.cpython-312.pyc
Labels: ✨ Feature

#30 [Feat] 설정페이지 UI 추가, Util 파일 추가
  Color.py
  SettingPage.py
  SnakeAndApple.py
  StartPage.py
  Util.py
Labels: ✨ Feature

#32 [Fix] 한글 깨짐 현상 수정
  Color.py
  SettingPage.py
  SnakeAndApple.py
  StartPage.py
Labels: ⚒️ Fix

#39 [Feat] 보드칸 크기 설정
  Color.py
  SettingPage.py
  SnakeAndApple.py
  StartPage.py
Labels: ✨ Feature

#42 [Feat] 독사과 기능 구현
  SettingPage.py
  SnakeAndApple.py
  StartPage.py
Labels: ✨ Feature

#43 feature-뱀 색상 기능 추가
  Color.py
  SettingPage.py
  SnakeAndApple.py
  StartPage.py
Labels: ✨ Feature

#47 [Refactor] 변수명, 함수명 스네이크 표기법으로 변환
  SettingPage.py
  StartPage.py
Labels: ⚙️ Refactor

#45 [Feat] 시작페이지 돌아가기 추가
  SnakeAndApple.py
  StartPage.py
Labels: ✨ Feature

#49 [Fix] 색상 버그 수정
  Color.py
  SettingPage.py
Labels: ⚒️ Fix

#50 [Feat] 사과 이미지 적용
  SnakeAndApple.py
  StartPage.py
  images/apple.png
  images/poison_apple.png
Labels: ✨ Feature

#56 [Refactor / Feat] 코드 최적화, 독사과 음향효과 추가
  Images.py
  SettingPage.py
  SnakeAndApple.py
  Sounds.py
  StartPage.py
  main.py
  sounds/eatingpoison.wav
Labels: ⚙️ Refactor, ✨ Feature
